# Generated by Django 5.1.4 on 2024-12-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email')),
                ('country', models.CharField(max_length=255, verbose_name='Estado')),
                ('status', models.IntegerField(choices=[(0, 'Ativo'), (1, 'Desativado')], default=0)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
